window.TEXTS={
    'item.quickstart':['Quick start','入門篇'],
    'item.dom':['Dom operation','DOM操作'],
    'item.events':['Event & delegate','Event & delegate'],
    'item.app':['Application','Application'],
    'item.ctrl':['View Controller','View Controller'],
    'item.super':['View Inheritance','View Inheritance'],
    'item.view':['Custom components','Custom components'],
    'item.template':['Template','Template'],
    'item.state':['State','State'],
    'item.if':['$if','$if'],
    'item.for':['$for','$for'],
    'item.visibility':['visibility','表示切替'],
    'item.list':['list','list'],
    'item.form':['form','form'],
    'item.practice':['Best practice','推奨の構造'],
    'item.autocomplete':['autocomplete','autocomplete'],
    'item.popup':['popup','popup'],
    'item.slider':['slider','slider'],
    'item.selection':['selection','selection'],
    'item.tabmenu':['tabmenu','tabmenu'],
    'item.ma_settings' : ['settings', 'settings'],
    'item.ma_ctrl' : ['view controller', 'view controller'],
    'item.ma_css' : ['CSS', 'CSS'],
    'item.ma_command' : ['commands', 'commands'],
    'item.$':['$','$'],
    'item.string':['String','String'],
    'item.array':['Array','Array'],
    'item.date':['Date','Date'],
    'item.element':['Element','Element'],
    'item.nodelist':['NodeList','NodeList'],
    'item.http':['http','http'],


    'view.quickstart_view':['Quick start','Quick start'],
    'view.dom_view':['Dom manipulation','Dom manipulation'],
    'view.ctrl_view':['View Controller','View Controller'],
    'view.events_view':['Events driven & delegate model','Events driven & delegate model'],
    'view.template':['Template','Template'],
    'view.super_view':['View Inheritance','画面の継承'],
    'view.if_view':['if conditions','if conditions'],
    'view.for_view':['for loop','for loop'],
    'view.visibility_view':['visibility','visibility'],
    'view.list_view':['UI ListView','UI ListView'],
    'view.form_view':['UI FormView','UI FormView'],
    'view.autocomplete_view':['Autocomplete','Autocomplete'],
    'view.popup_view':['Popup','Popup'],
    'view.slider_view':['Slider','Slider'],
    'view.selection_view':['Selection','Selection'],
    'view.tabmenu_view':['Tabmenu','Tabmenu'],
    'view.practice_view':['Best practice','推奨の構造'],
    'view.ma_settings_view':['Miniapp SDK environment settings', 'Miniapp SDK environment settings'],
    'view.ma_ctrl_view':['Miniapp view controller', 'Miniapp view controller'],
    'view.ma_css_view':['Miniapp CSS guideline', 'Miniapp CSS guideline'],
    'view.ma_command_view':['Miniapp SDK commands', 'Miniapp SDK commands'],
    'view.any_view':['$ functions','$ functions'],
    'view.string_view':['String','String'],
    'view.array_view':['Array','Array'],
    'view.date_view':['Date','Date'],
    'view.element_view':['Element','Element'],
    'view.nodelist_view':['NodeList','NodeList'],
    'view.http_view':['http','http'],
    'view.top_view':['anybot JS library','anybot JS library'],
}